---
- name: Install and configure AIDE for filesystem integrity
  become: true
  when: ansible_virtualization_type not in ['docker', 'lxc', 'podman', 'container']
  tags:
    - aide
    - hardening
  block:
    - name: Install AIDE package
      ansible.builtin.package:
        name: aide
        state: present

    - name: Initialize AIDE database if it does not exist
      ansible.builtin.command: aide --init
      args:
        # This command is slow, so we only run it if the new DB doesn't exist
        creates: /var/lib/aide/aide.db.new.gz
      changed_when: true
      notify: Copy aide database

    - name: Enable and start AIDE check timer
      ansible.builtin.systemd_service:
        name: aidecheck.timer
        state: started
        enabled: true
