---
- name: Ensure /etc/modprobe.d directory exists
  ansible.builtin.file:
    path: /etc/modprobe.d
    state: directory
    mode: '0755' # Or whatever permissions are appropriate for this directory
    owner: root
    group: root

- name: Ensure /tmp is configured as a tmpfs with secure mount options
  ansible.posix.mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: rw,nosuid,nodev,noexec
    state: mounted
  become: true
  when: hardening_configure_tmp
  tags:
    - mount
    - hardening

- name: Ensure /var/tmp is bind-mounted to /tmp for security
  ansible.posix.mount:
    path: /var/tmp
    src: /tmp
    fstype: none
    opts: bind
    state: mounted
  become: true
  when: hardening_bind_var_tmp
  tags:
    - mount
    - hardening

- name: Ensure separate partitions are configured in /etc/fstab
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state | default('mounted') }}"
  become: true
  loop: "{{ hardening_partitions }}"
  when:
    - item.src is defined
    - item.src | length > 0
  tags:
    - mount
    - hardening
