---
- name: Harden sudo configuration
  become: true
  when:
    - ansible_virtualization_type not in ['docker', 'lxc', 'podman', 'container']
  tags:
    - sudo
    - hardening
  block:
    - name: 1.3.1 Ensure sudo is installed (Scored)
      ansible.builtin.package:
        name: sudo
        state: present
      when:
        - cis_sudo_installed | bool

    - name: 1.3.2 Ensure sudo commands use pty (Scored)
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/use_pty.conf
        mode: "0600"
        line: 'Defaults use_pty'
        create: true
      when:
        - cis_sudo_use_pty | bool

    - name: 1.3.3 Ensure sudo log file exists (Scored)
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/logfile.conf
        mode: "0440"
        line: 'Defaults logfile="/var/log/sudo.log"'
        create: true
        validate: '/usr/sbin/visudo -cf %s'
      when:
        - cis_sudo_logfile | default(true) | bool
